name: Rust CI

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          -  5432:5432
        options: --health-cmd pg_isready --health-interval  10s --health-timeout  5s --health-retries  5

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --all-features